// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz_cSo10zfZ_5UocYYMDiXgoDF0SJJG-U',
    appId: '1:586307952197:web:1c536a0ccabb1ba7b74d2c',
    messagingSenderId: '586307952197',
    projectId: 'mirrorme-733ea',
    authDomain: 'mirrorme-733ea.firebaseapp.com',
    storageBucket: 'mirrorme-733ea.firebasestorage.app',
    measurementId: 'G-PD95HJEXWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpoZa54qqvM-3DgFLGAY5CLIDk1a-jFDU',
    appId: '1:586307952197:android:9104382d8f22f65eb74d2c',
    messagingSenderId: '586307952197',
    projectId: 'mirrorme-733ea',
    storageBucket: 'mirrorme-733ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWqxH6a22roFk-5dHduZKlKfTdiZnpR5g',
    appId: '1:586307952197:ios:6764c9ce9b79fc2fb74d2c',
    messagingSenderId: '586307952197',
    projectId: 'mirrorme-733ea',
    storageBucket: 'mirrorme-733ea.firebasestorage.app',
    iosBundleId: 'com.example.mirrorMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWqxH6a22roFk-5dHduZKlKfTdiZnpR5g',
    appId: '1:586307952197:ios:6764c9ce9b79fc2fb74d2c',
    messagingSenderId: '586307952197',
    projectId: 'mirrorme-733ea',
    storageBucket: 'mirrorme-733ea.firebasestorage.app',
    iosBundleId: 'com.example.mirrorMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz_cSo10zfZ_5UocYYMDiXgoDF0SJJG-U',
    appId: '1:586307952197:web:47b8c6d8b3d66077b74d2c',
    messagingSenderId: '586307952197',
    projectId: 'mirrorme-733ea',
    authDomain: 'mirrorme-733ea.firebaseapp.com',
    storageBucket: 'mirrorme-733ea.firebasestorage.app',
    measurementId: 'G-TT3V80YF5H',
  );
}
